### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by q623928815**

### CODE REVIEW

**Comment by q623928815** [comment]
with out that I got error........

**Comment by wookietreiber** [comment]
I can reproduce:

```console
$ make HTSSRC=../htslib angsd
HTSSRC defined
...
g++ -I/home/umcdev/src/htslib -O3 -D__WITH_POOL__  -o angsd *.o -lz -lm -lbz2 -llzma -lpthread -lcurl /home/umcdev/src/htslib/libhts.a
/usr/bin/ld: /home/umcdev/src/htslib/libhts.a(hfile_s3.o): undefined reference to symbol 'HMAC@@OPENSSL_1_1_0'
/usr/lib/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:70: angsd] Error 1
```

It occurs if the following conditions are met:

1.  you use `make HTSSRC=../htslib`
1.  that **htslib** was built with **curl** support
1.  that **curl** is built with **openssl** support, **openssl** has `libssl.so` and `libcrypto.so`

To fix this, you need to add `-lcrypto`.

**Comment by wookietreiber** [comment]
I guess, this PR can be closed because it was fixed in #169.

**Comment by ANGSD** [comment]
Hi I am closing this pull requests.

**Pull request closed without merging**
