### PR TITLE
fixed bug with unlogged banded SAF output in -doSaf 4 (beagle input)

### PR DESCRIPTION
**Pull request by nspope**
I introduced a functionality-breaking bug when converting the beagle-to-SAF pathway (-doSaf 4) to the new banded algorithm -- sorry! The output was not saved correctly (in log scale). This PR fixes the issue. 

As it seems this feature doesn't have tests, I'll add those in a follow-up PR. It looks like the non-banded, pre-0.937 version of -doSaf 4 may have had issues of its own, so I'll make up some test cases by hand.

### CODE REVIEW

**Comment by nspope** [comment]
It seems like the new test from #492 is failing ... I didn't touch anything in the beagle reader so not sure why it's breaking when I merge into this fork. @isinaltinkaya any idea what could be going wrong? Here is the relevant part of the log when I run it locally,
```
        -> angsd version: 0.937-85-g1f3b31a-dirty (htslib: 1.13-3-gd16bed5) build(May 30 2022 11:43:09)
        -> ../angsd -doMaf 4 -beagle beagle_reader/test3.beagle -fai beagle_reader/ref//ref3.fa.fai -out beagle_reader/test_results//test3
        -> Inputtype is beagle
        -> Problem finding chr:chr from faifile
        -> angsd version: 0.937-85-g1f3b31a-dirty (htslib: 1.13-3-gd16bed5) build(May 30 2022 11:43:09)
        -> ../angsd -doMaf 4 -beagle beagle_reader/test4.beagle -fai beagle_reader/ref//ref4.fa.fai -out beagle_reader/test_results//test4
        -> Inputtype is beagle
        -> Problem finding chr:chr from faifile
```

**Comment by nspope** [comment]
Hey @ANGSD, could we merge this bugfix in soon?

**Comment by isinaltinkaya** [comment]
Conflicts are resolved in #500

**Comment by isinaltinkaya** [comment]
Bug introduced by if(1||isSim) accessing nonexistent gls through `dosaf 4`  and conflicts are resolved in #500.

**Pull request closed without merging**
