### PR TITLE
makes build more portable

### PR DESCRIPTION
**Pull request by wookietreiber**
These commits make the build more portable.

### CODE REVIEW

**Comment by wookietreiber** [comment]
That's it for now:

- fixes #170 and #171
- the build is more flexible in terms of what users can specify, what gets overridden
- the build is simpler (diff stat to both Makefiles: 81 insertions, 140 deletions)
- travis is 1.5 minutes faster (from 5.5 minutes to 3-4 minutes)

I hope the reasoning for these changes is clear enough from the commit messages. If not or you have questions in general, feel free to ask and to review the changes.

**Comment by ANGSD** [comment]
Ok sounds super! This is very much appreciated. Thanks for taking your
time. Ill include it and make sure you get credited properly!

Thanks for you help with this.

2018-07-26 15:47 GMT+02:00 ♫ Christian Krause ♫ <notifications@github.com>:

**Comment by ANGSD** [comment]
Hi was just looking at this. On what system is the lcrypto required?

Thanks!

**Comment by wookietreiber** [comment]
As I've written in #151 it depends on how **htslib** is built.

**Comment by ANGSD** [comment]
Ok super it looks very nice. Thanks for taking your time to do this. It is very much appreciated. Ive now merged it into the main angsd.

**Comment by wookietreiber** [comment]
You're welcome!

**Pull request merged**
